Feature: Renew Fleet feature
Scenario: IRP Renew fleet
Given User login as a Internal user
When User will navigate to the IRPLink
Then User will provide all the Account Number Details to start with IRP Transaction
Then User will navigate to account section and fill the data and validate message "IRPFLT143 : [W] Fleet information [USDOT No.] in the system does not match with the MCE information."
Then User will navigate to Fleet section and fill the data and validate message "GEN1292 : [I] USDOT No. has been updated based on the MCE information." "IRPFLT129 : [I] Account has 0 power unit fleet(s) for 2023. Account has 1 power unit fleet(s) for 2022." "IRPACC00 : [I] Renewal account has been generated."
Then User will navigate to Distance section and fill the data and validate message "IRPFLT01 : [I] Renewal fleet has been generated." "[I] MCE: IRP status successfully updated." "IRPMLG25 : [W] Mileage appears rounded please verify."
Then User will navigate to Weight group section and fill the data ans validate message "IRPMLG13 : [I] Renewal Distance has been generated."
Then User will navigate to add, amend vehicle as per the requirement and Validate the message "IRPVEH375 : [I] Please search the VIN first to process a vehicle." "IRPVEH491 : [W] New Plate Required flag set for this vehicle to Yes." "IRPVEH004 : [I] Vehicle amended successfully."
Then User will Delete Vehicle as per the requiremnet and navigate to billing validate the message "IRPVEH450 : [W] Unit(s) [6266] have no plate assigned. If you continue a new plate will be assigned or select 'Update from Previous Year' button or amend the vehicle and check 'Use Existing Plate' option to not issue a new plate." "IRPVEH246 : [I] Vehicle(s) deleted successfully." "GEN1062 : [I] Cancellation completed successfully." "IRPBILL09 : [E] Manual adj. reason is required." "IRPBILL08 : [E] Fee Override reason required."
And User will navigate to Payment Tab and fill the requirement and validate message "GEN24 : [I] Invoice report generated successfully." "IRPREP28 : [I] Billing completed successfully." "GEN1239 : [I] TVR generated successfully."
And User will navigate to Supplementary Tab and validate the meesage "GENPAY01 : [E] This transaction already exists in the cart."
And User will navigate to payment tab and Fill the requirement 
Then user will Validate Message "VIN: 6N66X99X66N637825, UnitNo: 6266, Reason:IRPCRED2 : [E] PWR [66000] Type plate is not available for User: internaluser, Office Location: HQ." "GEN1306 : [I] Credentials requested: 4, Credentials successful: 3, Credentials failed: 1. [Account No.:11113, Fleet No.:001, Fleet Exp. Year:2023, Fleet Exp. Month:03, Supp. No.:000]""GEN24 : [I] Payment Receipt generated successfully.""GEN24 : [I] Credentials generated successfully."
Then User Navigate to inventry tab and fill the data and validate the message "ENTINV56 : [I] Length of From No. must be 6 with inventory format ##@@#@ where # must be numeric and @ must be alphabetic." "ENTINV06 : [I] Inventory has been added successfully."
Then user navite to Financetab and navigate to installment payment and fill the data and valite the message "PAY14 : [I] Payment completed successfully." "GEN24 : [I] Payment Receipt generated successfully."